### ISSUE TITLE
Support service keys

### ISSUE THREAD

**Issue by spiegela** [spring-cloud/spring-cloud-cloudfoundry-service-broker#35]
Add support for service keys which enable access to services by external access:

> ...the new Service Key feature is added as a new resource which essentially externalizes the old service binding operation, except it does not require an application to be called or manipulated. Like other CF Cloud Controller (CC) resources, this one has the typical CRUD operations (except update, but includes listing)...

The details of the service keys API doesn't seem to existing within the service broker documentation, yet, but is detailed here:

https://developer.ibm.com/opentech/2015/07/09/cloudfoundry-services-keys-and-sample-go-service-broker/

**Comment by scottfrederick** [comment]
@spiegela The service keys feature doesn't require explicit support in a service broker, which is why you don't see any mention of it in the [service broker API documentation](http://docs.cloudfoundry.org/services/api.html). When creating a service key from a service instance, CC calls the broker's binding API to get a set of credentials, and everything else is managed in CC.

**Comment by spiegela** [comment]
I see. So, if needed, I can distinguish between types of bindings and keys using the bind params. The IBM article probably needs an update since it shows specific routes.

Once I test, I'll let Dr. Max know.

Thanks!

-Aaron

**Comment by scottfrederick** [comment]
To be clear, routes in the article like `POST /v2/service_keys` and `GET /v2/service_keys` are routes to the CF API (i.e. Cloud Controller). The article doesn't show the interactions between CC and the service broker (unless that's in the video embedded in the article).
