### ISSUE TITLE
Support Service Broker API 2.12

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud/spring-cloud-cloudfoundry-service-broker#37]
http://docs.cloudfoundry.org/services/api.html#changes-since-v211

* Add `context` field to request body for provisioning and updating a service instance

**Comment by Samze** [comment]
Note that while the latest CF release (1.3.0) is sending the 2.12 context field it is still sending 2.11 in the `X-Broker-Api-Version` header. This was by design as we were waiting on consensus in the working group. 

That has now happened but we are waiting for this [PR](https://github.com/cloudfoundry/cloud_controller_ng/pull/835) to be accepted.

**Comment by mcelep** [comment]
@Samze your [PR](https://github.com/cloudfoundry/cloud_controller_ng/pull/835) is merged. I am happy to create a PR that implements 2.12 related changes.

**Comment by Samze** [comment]
Sounds good @mcelep. Yeah the OSBAPI 2.12 spec has been released.

**Comment by scottfrederick** [comment]
@Samze @mcelep I have some WIP changes for the `context` field change. I'm hoping to get those changes done this week.

**Comment by scottfrederick** [comment]
Fixed in https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/commit/8e5d87fad64e6c281afef0923d476a24fb629c65
