### ISSUE TITLE
Return status code 200 on provisioning/binding of already existing service instance/binding

### ISSUE THREAD

**Issue by madmichi** [spring-cloud/spring-cloud-cloudfoundry-service-broker#5]
The service broker API specification suggests that a status code 200 (OK) might be returned in the response of a provisioning/binding if a service instance/binding already exists.

**Comment by scottfrederick** [comment]
The [service broker API docs](http://docs.cloudfoundry.org/services/api.html#provisioning) currently have this:

Status Code | Description
---------------- | --------------
200 OK | May be returned if the service instance already exists and the requested parameters are identical to the existing service instance. The expected response body is below.
409 Conflict | Should be returned if the requested service instance already exists. The expected response body is {}.

This is a bit confusing and contradictory, but 409 seems like the more appropriate option as the broker is being asked to do something (e.g. provision a new service instance) that it can not do (because an instance already exists). 

What is the use case for returning a 200 instead of a 409?

**Comment by madmichi** [comment]
The use case would be that one tries to create a service instance with the exact same parameters as the already existing one. In that case there is no conflict. Everything is as expected, except there was nothing to do for the broker.
Whereas the 409 should be the response if the parameters are conflicting with the already created service instance.

**Comment by scottfrederick** [comment]
I think we can accomplish this with a flag in the `CreateServiceInstanceResponse` class to indicate whether the instance was actually created or already existed, and return either `200 OK`,  `201 CREATED` or `202 ACCEPTED` depending on the value of the "existing" and "async" flags.

**Comment by madmichi** [comment]
That sounds great to me.

**Comment by mheath** [comment]
@madmichi I'm not sure I understand what problem this solves. The CC is the only service broker client and CC doesn't do anything different whether it's a `200` or `201` response. https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/services/service_brokers/v2/response_parser.rb#L15-L20

Do you have a custom Service Broker API client? Or is this for automated testing purposes?

**Comment by madmichi** [comment]
Hello @mheath ,
no, we have no custom client and yes, we have tests expecting the 200 from our old broker implementation.
It would be no problem to change the tests but we wanted to adhere to the spec.
Do you see too much expense in doing so?

**Comment by mheath** [comment]
@madmichi Sorry for taking so long to reply.

This wouldn't be terribly difficult to implement. My concern is that adding something to the API that doesn't change behavior could be seen as cluttering the API.

After thinking about this though, I can see how using a 201 response to indicate that the service was created and a 200 response to indicate the service already exists could be useful for automated testing purposes.

**Comment by madmichi** [comment]
I agree, a sleek API is worthwhile, but we would be glad if you see the added value.

**Comment by scottfrederick** [comment]
Fixed in https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/commit/a1fe85669cfd3c749d2c2540cd86316038c023ac.

**Comment by scottfrederick** [comment]
@madmichi This change should be available in a `1.0.0.BUILD-SNAPSHOT` version at repo.spring.io/build-snapshot soon. When you can test it out and make sure it works for you, I will close this issue.

**Comment by madmichi** [comment]
Thanks a lot Scott, I will test as soon as possible and report back.
