### ISSUE TITLE
Enable Gradle Checkstyle plugin

### ISSUE THREAD

**Issue by royclarkson** [spring-cloud/spring-cloud-cloudfoundry-service-broker#59]
Expect a consisting styling with Spring Boot
https://docs.gradle.org/current/userguide/checkstyle_plugin.html

**Comment by scottfrederick** [comment]
Fixed in https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/commit/1b673f6f96a326d8902f00e295b790a0777c34c5

Using the PMD plugin instead of CheckStyle, for consistency with the [codacy](https://app.codacy.com/app/scottfrederick/spring-cloud-cloudfoundry-service-broker/) checks.
